// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: api/sso_server_v1/sso.proto

package sso_server_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SsoV1_VerifyToken_FullMethodName = "/sso_server_v1.SsoV1/VerifyToken"
)

// SsoV1Client is the client API for SsoV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SsoV1Client interface {
	VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error)
}

type ssoV1Client struct {
	cc grpc.ClientConnInterface
}

func NewSsoV1Client(cc grpc.ClientConnInterface) SsoV1Client {
	return &ssoV1Client{cc}
}

func (c *ssoV1Client) VerifyToken(ctx context.Context, in *VerifyTokenRequest, opts ...grpc.CallOption) (*VerifyTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTokenResponse)
	err := c.cc.Invoke(ctx, SsoV1_VerifyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SsoV1Server is the server API for SsoV1 service.
// All implementations must embed UnimplementedSsoV1Server
// for forward compatibility.
type SsoV1Server interface {
	VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error)
	mustEmbedUnimplementedSsoV1Server()
}

// UnimplementedSsoV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSsoV1Server struct{}

func (UnimplementedSsoV1Server) VerifyToken(context.Context, *VerifyTokenRequest) (*VerifyTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyToken not implemented")
}
func (UnimplementedSsoV1Server) mustEmbedUnimplementedSsoV1Server() {}
func (UnimplementedSsoV1Server) testEmbeddedByValue()               {}

// UnsafeSsoV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SsoV1Server will
// result in compilation errors.
type UnsafeSsoV1Server interface {
	mustEmbedUnimplementedSsoV1Server()
}

func RegisterSsoV1Server(s grpc.ServiceRegistrar, srv SsoV1Server) {
	// If the following call pancis, it indicates UnimplementedSsoV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SsoV1_ServiceDesc, srv)
}

func _SsoV1_VerifyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SsoV1Server).VerifyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SsoV1_VerifyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SsoV1Server).VerifyToken(ctx, req.(*VerifyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SsoV1_ServiceDesc is the grpc.ServiceDesc for SsoV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SsoV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sso_server_v1.SsoV1",
	HandlerType: (*SsoV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyToken",
			Handler:    _SsoV1_VerifyToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/sso_server_v1/sso.proto",
}
