basePath: /api/v1
definitions:
  ad.HandleFavoriteRequest:
    properties:
      ad_id:
        type: integer
    type: object
  ad.ListResponse:
    properties:
      ads:
        items:
          $ref: '#/definitions/ad.Response'
        type: array
      range:
        $ref: '#/definitions/pagination.ListRange'
    type: object
  ad.Response:
    properties:
      brand:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      is_favorite:
        type: boolean
      is_token_minted:
        type: boolean
      model:
        type: string
      price:
        type: number
      title:
        type: string
      updated_at:
        type: string
      vin:
        type: string
      year_of_release:
        type: integer
    type: object
  ad.StoreRequest:
    properties:
      brand:
        type: string
      description:
        type: string
      model:
        type: string
      price:
        type: number
      title:
        type: string
      vin:
        type: string
      year_of_release:
        type: integer
    type: object
  handler.BasicResponseDTO:
    properties:
      data: {}
      status:
        type: integer
    type: object
  handler.ErrorResponse:
    properties:
      error:
        example: chat
        type: string
    type: object
  nft.NFT:
    properties:
      chain_id:
        type: integer
      chain_name:
        type: string
      contract_addr:
        type: string
      token_id:
        type: integer
      token_metadata:
        $ref: '#/definitions/nft.TokenMetadata'
      token_url:
        type: string
    type: object
  nft.TokenMetadata:
    properties:
      attributes:
        items:
          properties:
            trait_type:
              type: string
            value:
              type: string
          type: object
        type: array
      description:
        type: string
      image:
        type: string
      name:
        type: string
    type: object
  pagination.ListRange:
    properties:
      count:
        type: integer
      page:
        type: integer
      per_page:
        type: integer
    type: object
  payment.Response:
    properties:
      ad_id:
        type: integer
      confirmation_link:
        type: string
      created_at:
        type: string
      expires_at:
        type: string
      id:
        type: integer
      status:
        type: string
      tariff:
        $ref: '#/definitions/tariff.Tariff'
      transaction_id:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  payment.StatusChangedResponse:
    properties:
      status:
        type: string
    type: object
  tariff.Tariff:
    properties:
      createdAt:
        type: string
      currency:
        type: string
      description:
        type: string
      durationMin:
        type: integer
      id:
        type: integer
      isActive:
        type: boolean
      name:
        type: string
      price:
        type: number
      updatedAt:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: http://localhost:8989
info:
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Ads Service API
  version: "1.0"
paths:
  /api/v1/ads:
    get:
      consumes:
      - application/json
      description: Get paginated and filtered list of ads
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Items per page
        in: query
        name: limit
        type: integer
      - description: Filter criteria (key=value)
        in: query
        name: filter
        type: string
      - description: Sort field and direction (field=asc|desc)
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.BasicResponseDTO'
            - properties:
                data:
                  $ref: '#/definitions/ad.ListResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get ads list
      tags:
      - Ads
    post:
      consumes:
      - application/json
      description: Create new car advertisement
      parameters:
      - description: Ad data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ad.StoreRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/handler.BasicResponseDTO'
            - properties:
                data:
                  $ref: '#/definitions/ad.Response'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create new advertisement
      tags:
      - Ads
  /api/v1/ads/{adId}/nft:
    get:
      consumes:
      - application/json
      description: Get NFT information for ad
      parameters:
      - description: Ad ID
        in: path
        name: adId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.BasicResponseDTO'
            - properties:
                data:
                  $ref: '#/definitions/nft.NFT'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get NFT metadata
      tags:
      - NFT
  /api/v1/ads/{id}:
    delete:
      consumes:
      - application/json
      description: Delete car advertisement
      parameters:
      - description: Ad data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ad.StoreRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/handler.BasicResponseDTO'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete advertisement
      tags:
      - Ads
    get:
      consumes:
      - application/json
      description: Get car advertisement details
      parameters:
      - description: Ad ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.BasicResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get advertisement by ID
      tags:
      - Ads
    patch:
      consumes:
      - application/json
      description: Update new car advertisement
      parameters:
      - description: Ad data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ad.StoreRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/handler.BasicResponseDTO'
            - properties:
                data:
                  $ref: '#/definitions/ad.Response'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update new advertisement
      tags:
      - Ads
  /api/v1/favorites:
    post:
      consumes:
      - application/json
      description: Toggle ad in user's favorites
      parameters:
      - description: Ad ID
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/ad.HandleFavoriteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.BasicResponseDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Add/remove ad to favorites
      tags:
      - Favorites
  /api/v1/payments:
    post:
      consumes:
      - application/json
      description: Регистрация платежа и генерация ссылки
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.BasicResponseDTO'
            - properties:
                data:
                  $ref: '#/definitions/payment.Response'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Создание платежа
      tags:
      - Payments
  /api/v1/payments/webhook:
    post:
      consumes:
      - application/json
      description: Обработка вебхука и смена статуса платежа
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.BasicResponseDTO'
            - properties:
                data:
                  $ref: '#/definitions/payment.StatusChangedResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Нотификация платежа
      tags:
      - Payments
swagger: "2.0"
